@isTest
public class Test_Base311_TriggerHandler_ServiceQueue {

    @isTest
    static void testAfterInsert() {
        /*List<Service_Queue__c> sqs = new List<Service_Queue__c>();
        
        sqs.add(new Service_Queue__c(Name = 'Test1'));
        sqs.add(new Service_Queue__c(Name = 'Test2'));
        
        insert sqs;
        
        List<String> names = new List<String>{ 'Test1', 'Test2' };
        
        List<Group> groups = [SELECT Id, DeveloperName, Name FROM Group WHERE Name IN :names ORDER BY Name];
        
        System.assertEquals(groups.size(), 2);
        System.assertEquals(groups[0].Name, 'Test1');
        System.assertEquals(groups[1].Name, 'Test2');*/
    }
    
}